[package]
name = "princhess-train"
version = "0.0.0-dev"
edition = "2021"
publish = false

[dependencies]
arrayvec = { workspace = true }
bytemuck = { workspace = true }
princhess = { path = "../../", default-features = false }
ratatui = "=0.29.0"
crossterm = "=0.28.1"
scc = { workspace = true }
